FROM openresty/openresty:xenial

MAINTAINER Stanislav WEB "stanisov@gmail.com"

RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-jwt

COPY ./server/nginx.conf /nginx.conf
COPY ./server/lib/bearer.lua /bearer.lua

ENTRYPOINT ["/usr/local/openresty/bin/openresty", "-g", "daemon off;", "-c", "/nginx.conf"]

EXPOSE 88