nginx:
    build: .
    dockerfile: Dockerfile.nginx
    links:
        - app
    ports:
        - "88:88"

app:
    build: .
    dockerfile: Dockerfile.python
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    ports:
        - "5000:5000"