nginx:
    build: .
    dockerfile: Dockerfile.nginx
    links:
        - app
    volumes:
     - /app/images
    ports:
        - "88:88"

app:
    build: .
    restart: always
    dockerfile: Dockerfile.python
    volumes:
     - /app/images
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    ports:
        - "5000:5000"